### ISSUE TITLE
Prism homepage link is broken

### ISSUE THREAD

**Issue by olivernagy** [OAI/tools.openapis.org#122]
**Describe the bug**
Clicking the Homepage link for Prism takes you to a 404 page.

**To Reproduce**
1. Go to https://tools.openapis.org/categories/mock.html
2. Click "Link" in the Homepage column in the Prism row.
3. A 404 error page opens

**Expected behavior**
An existing page should show.

**Screenshots**
![image](https://github.com/OAI/Tooling/assets/1309541/aa362396-1c59-4b45-94a9-b0d35415512a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version 120.0.6099.216

**Additional context**
The correct link is https://stoplight.io/open-source/prism

**Comment by SensibleWood** [comment]
@olivernagy thanks for raising this. It is broken in the source repository (https://openapi.tools) and, to date, we've just sucked in data from there. However using this as the opportunity to start to use this repository as source-of-truth so will work on fix under this ticket.
