### ISSUE TITLE
Add UI Bakery to the list of tools

### ISSUE THREAD

**Issue by lugovsky** [OAI/tools.openapis.org#137]
Hello there,

We are developing a low-code platform that works with OpenAPI which we believe could be a good addition to your list of tools.

## Tool Properties

- Display name: UI Bakery
- Description: A low-code platform to build user interfaces on top of OpenAPI data using drag and drop.
- Repository: https://github.com/uibakery/self-hosted
- Homepage: https://uibakery.io/

## OpenAPI Versions

- 3.1: true
- 3.0: true
- 2.0: false

**Comment by SensibleWood** [comment]
This was added successfully but automated close of issue failed. Closing manually.

**Comment by SensibleWood** [comment]
Reopening as data fix required... Issue was not read correctly

**Comment by lugovsky** [comment]
@SensibleWood Is the data fix required from my end? Could you please provide more details?

**Comment by SensibleWood** [comment]
@lugovsky no all on me 😉 just using your ticket to do the fix
